# Generated by Django 4.1.3 on 2022-11-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_url",
                    models.URLField(
                        help_text="Вставте ссылку для сокращения",
                        verbose_name="Сокращаемая ссылка",
                    ),
                ),
                ("nums_of_visits", models.PositiveIntegerField(default=0)),
                ("slug", models.SlugField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
